name: chemlab_frontend
description: Chemistry Laboratory Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  file_picker: ^5.3.3
  path_provider: ^2.1.1
  pdf: ^3.10.4
  csv: ^5.1.1
  flutter_local_notifications: ^15.1.1
  fluttertoast: ^8.2.4
  syncfusion_flutter_datagrid: ^22.2.12
  syncfusion_flutter_charts: ^22.2.12
  syncfusion_flutter_pdfviewer: ^22.2.12
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/